### PR TITLE
Added fontStyle and fontWeight. Fixes #916

### PR DESCRIPTION
**Pull request by NelGarbuzova**

### CODE REVIEW

**Comment by NelGarbuzova** [comment]
https://github.com/terrestris/geostyler/issues/916

**Comment by marcjansen** [comment]
Hi @NelGarbuzova, thanks.

I fear this is not the right fix, but am confident that maybe @KaiVolland or @jansule may have some pointers wrt how an implementation could look like.

**Comment by KaiVolland** [comment]
@marcjansen is right.

We first need to support `font-weight` and `font-style` in the [`TextSymbolizer` in the `geostyler-style`](https://github.com/terrestris/geostyler-style/blob/master/index.d.ts#L142).

@NelGarbuzova would you like to do a PR over there, too? Should be just something like:

```ts
fontWeight?: string;
fontStyle?: string;
```
If so, please extend the [sample](https://github.com/terrestris/geostyler-style/blob/master/sample.ts#L47) accordingly.

**Comment by NelGarbuzova** [comment]
https://github.com/terrestris/geostyler-style/pull/114

**Comment by NelGarbuzova** [comment]
https://github.com/terrestris/geostyler-style/pull/115

**Comment by jansule** [comment]
This PR is not being maintained anymore.
=> Closing

**Pull request closed without merging**
